// Regenerate ui/theme.tokens.css from the frontend's own stylesheet.
//
//   npm run sync-theme
//
// The shell's chrome — the bar and the launcher — has to paint in Gamma's
// colours, including whichever theme the page reports. Copying the values by
// hand guarantees they drift, and chrome that is *nearly* the right grey looks
// worse than chrome that is plainly separate. So they are extracted, and this
// script is the way to pick up a change to app.css.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "..", "..");
const source = path.join(repo, "frontend", "src", "app.css");
const target = path.join(here, "..", "ui", "theme.tokens.css");

const css = fs.readFileSync(source, "utf8");

/** The custom-property declarations of one rule, in source order. */
function tokens(selector) {
  const start = css.indexOf(`${selector} {`);
  if (start < 0) throw new Error(`no ${selector} rule in app.css`);
  const end = css.indexOf("\n}", start);
  const body = css.slice(start + selector.length + 2, end);
  const kept = body.split("\n").filter((line) => /^\s*--[a-z0-9-]+:/.test(line));
  if (!kept.length) throw new Error(`no custom properties in ${selector}`);
  return `${selector} {\n${kept.join("\n")}\n}\n`;
}

const header = `/* Gamma's design tokens, extracted from frontend/src/app.css.
 *
 * Generated by desktop/scripts/sync-theme.mjs — do not edit by hand.
 * The themes are the ones the app itself defines; "dark" is :root's default.
 */
`;

// :root carries dark, the default; the rest override it per data-theme.
const out = [header, tokens(":root")];
for (const theme of ["light", "sepia", "gray"]) {
  out.push(tokens(`[data-theme="${theme}"]`));
}

fs.writeFileSync(target, out.join("\n"));
const count = out.join("\n").split("\n").filter((l) => l.trim().startsWith("--")).length;
console.log(`wrote ${path.relative(process.cwd(), target)} — ${count} tokens, 4 themes`);
